hydra:
  job:
    name: SimCLR
  run:
    dir: ./experiments/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

dataset:
  train_ratio: 0.9
  clip_dur: 1
  sample_rate: 16000
  n_mels: 64
  hop_len: 200
  segment_dur: 10
  contrastive: True

train:
  method: SimCLR
  model_name: na
  batch_size: 32
  lr: 5e-4
  check_monitor: val_acc_top5
